### PR TITLE
some small issues

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by alexeiva** [comment]
Thanks, @schriftgestalt!
`softhyphen` is a spacing character. I don't want it to have actual kerning in case of `hyphen`, so I rather remove it. 

I have a question:
I assigned different values to `i` and `idotless`. When I run the script, it gives `i`, and all combining `iacute`, `igrave` values from `idotless`.

Similarly `Hbar` was assigned its own classes, but inherited values from `H`.
Is this a built-in function in the script, or in Glyphs App?

Is there a way to override it?

**Comment by alexeiva** [comment]
I found the answer:
1. If `Hbar` is decomposed is gets the value from the script, i.e. `Hbar`
2. If `Hbar` is composed, it's inherits the value from `H`
   screen shot 2016-07-29 at 09 18 00

Is there a way to do option 1 without decomposing the glyphs?

**Comment by schriftgestalt** [comment]
The softhyhen should look exactly as the hyphen. So it should be in the same class.

**Comment by schriftgestalt** [comment]
The script has to ways to assign groups. One is the list and the other are existing components. This is checked in line 1258 to 1280. There are two options. To always prefer the entries from the list or to add a switch that overwrites components with the value from the list.

**Comment by alexeiva** [comment]
Thanks for clarifying, Georg! About the softhyphen: there are two standards. What you mentioned is the Unicode definition. I prefer the other, invisible soft hyphen, used for marking were a word should be hyphenated. This is more practical IMO.

**Comment by schriftgestalt** [comment]
You are right. I mixed that up. So it needs no kerning group at all.

**Pull request merged**
